services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /Users/blouminn/Documents/code/piscine_data_science/database:/var/lib/postgresql/data
    env_file:
      - .env
