services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - /Users/blouminn/Documents/code/piscine_data_science/database:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "5050:80"
    networks:
      - postgres
    volumes:
      - /Users/blouminn/Documents/code/piscine_data_science/database:/var/lib/pgadmin
    env_file:
      - .env

networks:
  postgres:
    driver: bridge
